// <auto-generated />
namespace Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fghjk1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fghjk1));
        
        string IMigrationMetadata.Id
        {
            get { return "202006290026479_fghjk1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
