// <auto-generated />
namespace Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fvghjk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fvghjk));
        
        string IMigrationMetadata.Id
        {
            get { return "202006231651429_fvghjk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
