//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hospital.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهادة صيانة دورية.
        /// </summary>
        public static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و الجهاز يعمل بحالة جيدة.
        /// </summary>
        public static string a10 {
            get {
                return ResourceManager.GetString("a10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهندس الشركة.
        /// </summary>
        public static string a11 {
            get {
                return ResourceManager.GetString("a11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم.
        /// </summary>
        public static string a12 {
            get {
                return ResourceManager.GetString("a12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيع.
        /// </summary>
        public static string a13 {
            get {
                return ResourceManager.GetString("a13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيس القسم.
        /// </summary>
        public static string a14 {
            get {
                return ResourceManager.GetString("a14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم الهندسي للمستشفى.
        /// </summary>
        public static string a15 {
            get {
                return ResourceManager.GetString("a15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الختم.
        /// </summary>
        public static string a16 {
            get {
                return ResourceManager.GetString("a16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير المركز الصحي.
        /// </summary>
        public static string a17 {
            get {
                return ResourceManager.GetString("a17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز صحي.
        /// </summary>
        public static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الكمبيوتر.
        /// </summary>
        public static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجهاز.
        /// </summary>
        public static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التسلسل.
        /// </summary>
        public static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string a50 {
            get {
                return ResourceManager.GetString("a50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة المنتجة.
        /// </summary>
        public static string a6 {
            get {
                return ResourceManager.GetString("a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموديل.
        /// </summary>
        public static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و ذلك عن فترة الصيانة من تاريخ.
        /// </summary>
        public static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلي تاريخ.
        /// </summary>
        public static string a9 {
            get {
                return ResourceManager.GetString("a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Place.
        /// </summary>
        public static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show With Logo.
        /// </summary>
        public static string AboveLogo {
            get {
                return ResourceManager.GetString("AboveLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Data.
        /// </summary>
        public static string AccountData {
            get {
                return ResourceManager.GetString("AccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Device Request.
        /// </summary>
        public static string AddDeviceRequest {
            get {
                return ResourceManager.GetString("AddDeviceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, Choose A Device.
        /// </summary>
        public static string AddDevices {
            get {
                return ResourceManager.GetString("AddDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PPM Request.
        /// </summary>
        public static string AddPPMRequest {
            get {
                return ResourceManager.GetString("AddPPMRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Out Of Service.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Service Devices Chart.
        /// </summary>
        public static string ArchiveChart {
            get {
                return ResourceManager.GetString("ArchiveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Number Of Devices Are Out Of Service.
        /// </summary>
        public static string ArchiveCount {
            get {
                return ResourceManager.GetString("ArchiveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Date.
        /// </summary>
        public static string ArchiveDate {
            get {
                return ResourceManager.GetString("ArchiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure To Delete Row ?.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب أصلاح.
        /// </summary>
        public static string b1 {
            get {
                return ResourceManager.GetString("b1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الأنتهاء.
        /// </summary>
        public static string b10 {
            get {
                return ResourceManager.GetString("b10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زيارات أصلاح أوامر العمل.
        /// </summary>
        public static string b11 {
            get {
                return ResourceManager.GetString("b11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منفذ العمل.
        /// </summary>
        public static string b12 {
            get {
                return ResourceManager.GetString("b12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الزيارة.
        /// </summary>
        public static string b13 {
            get {
                return ResourceManager.GetString("b13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الذهاب.
        /// </summary>
        public static string b14 {
            get {
                return ResourceManager.GetString("b14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت البدء.
        /// </summary>
        public static string b15 {
            get {
                return ResourceManager.GetString("b15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الأنتهاء.
        /// </summary>
        public static string b16 {
            get {
                return ResourceManager.GetString("b16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنجاز.
        /// </summary>
        public static string b17 {
            get {
                return ResourceManager.GetString("b17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤشر.
        /// </summary>
        public static string b18 {
            get {
                return ResourceManager.GetString("b18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع الغيار المطلوبة.
        /// </summary>
        public static string b19 {
            get {
                return ResourceManager.GetString("b19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم أمر العمل.
        /// </summary>
        public static string b2 {
            get {
                return ResourceManager.GetString("b2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية.
        /// </summary>
        public static string b20 {
            get {
                return ResourceManager.GetString("b20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطعة.
        /// </summary>
        public static string b21 {
            get {
                return ResourceManager.GetString("b21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string b22 {
            get {
                return ResourceManager.GetString("b22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        public static string b23 {
            get {
                return ResourceManager.GetString("b23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع الغيار المستهلكة.
        /// </summary>
        public static string b24 {
            get {
                return ResourceManager.GetString("b24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الوحدة.
        /// </summary>
        public static string b25 {
            get {
                return ResourceManager.GetString("b25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القطعة.
        /// </summary>
        public static string b26 {
            get {
                return ResourceManager.GetString("b26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string b27 {
            get {
                return ResourceManager.GetString("b27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيعات.
        /// </summary>
        public static string b28 {
            get {
                return ResourceManager.GetString("b28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهندس الخدمات.
        /// </summary>
        public static string b29 {
            get {
                return ResourceManager.GetString("b29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجهاز.
        /// </summary>
        public static string b3 {
            get {
                return ResourceManager.GetString("b3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيس القسم.
        /// </summary>
        public static string b30 {
            get {
                return ResourceManager.GetString("b30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير المركز الصحي.
        /// </summary>
        public static string b31 {
            get {
                return ResourceManager.GetString("b31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير الصيانة.
        /// </summary>
        public static string b32 {
            get {
                return ResourceManager.GetString("b32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم.
        /// </summary>
        public static string b33 {
            get {
                return ResourceManager.GetString("b33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع.
        /// </summary>
        public static string b34 {
            get {
                return ResourceManager.GetString("b34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        public static string b35 {
            get {
                return ResourceManager.GetString("b35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        public static string b4 {
            get {
                return ResourceManager.GetString("b4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي.
        /// </summary>
        public static string b5 {
            get {
                return ResourceManager.GetString("b5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم الرئيسي.
        /// </summary>
        public static string b50 {
            get {
                return ResourceManager.GetString("b50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير المشروع.
        /// </summary>
        public static string b51 {
            get {
                return ResourceManager.GetString("b51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المركز الصحي.
        /// </summary>
        public static string b6 {
            get {
                return ResourceManager.GetString("b6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string b7 {
            get {
                return ResourceManager.GetString("b7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الطلب.
        /// </summary>
        public static string b8 {
            get {
                return ResourceManager.GetString("b8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الأنتهاء.
        /// </summary>
        public static string b9 {
            get {
                return ResourceManager.GetString("b9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Pervious Page.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Under Logo.
        /// </summary>
        public static string BottomLogo {
            get {
                return ResourceManager.GetString("BottomLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب وكيل.
        /// </summary>
        public static string c1 {
            get {
                return ResourceManager.GetString("c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأصلاح.
        /// </summary>
        public static string c10 {
            get {
                return ResourceManager.GetString("c10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string c11 {
            get {
                return ResourceManager.GetString("c11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأعطال.
        /// </summary>
        public static string c12 {
            get {
                return ResourceManager.GetString("c12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نتطلع الي العمل السريع الخاص بهذا الأعطال.
        /// </summary>
        public static string c13 {
            get {
                return ResourceManager.GetString("c13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اذا كان لديك اي استفسار بخصوص الأعطال لا تتردد.
        /// </summary>
        public static string c14 {
            get {
                return ResourceManager.GetString("c14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الأتصال بالصيانة الطبية علي الهاتف أو الفاكس.
        /// </summary>
        public static string c15 {
            get {
                return ResourceManager.GetString("c15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم :.
        /// </summary>
        public static string c16 {
            get {
                return ResourceManager.GetString("c16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهندس الصيانة.
        /// </summary>
        public static string c17 {
            get {
                return ResourceManager.GetString("c17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيع.
        /// </summary>
        public static string c18 {
            get {
                return ResourceManager.GetString("c18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string c19 {
            get {
                return ResourceManager.GetString("c19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحت الضمان.
        /// </summary>
        public static string c2 {
            get {
                return ResourceManager.GetString("c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحت عقد الباطن.
        /// </summary>
        public static string c3 {
            get {
                return ResourceManager.GetString("c3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة الوكيل.
        /// </summary>
        public static string c4 {
            get {
                return ResourceManager.GetString("c4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئول الشركة الوكيل.
        /// </summary>
        public static string c5 {
            get {
                return ResourceManager.GetString("c5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهندس المستشفي.
        /// </summary>
        public static string c50 {
            get {
                return ResourceManager.GetString("c50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاكس.
        /// </summary>
        public static string c6 {
            get {
                return ResourceManager.GetString("c6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إرسال المهندس المختص ل.
        /// </summary>
        public static string c7 {
            get {
                return ResourceManager.GetString("c7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تركيب.
        /// </summary>
        public static string c8 {
            get {
                return ResourceManager.GetString("c8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصيانة الوقائية.
        /// </summary>
        public static string c9 {
            get {
                return ResourceManager.GetString("c9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Archive.
        /// </summary>
        public static string CancelArchive {
            get {
                return ResourceManager.GetString("CancelArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Print PPM For A or B Desvices.
        /// </summary>
        public static string CannotPrintPPMForAorBDesvices {
            get {
                return ResourceManager.GetString("CannotPrintPPMForAorBDesvices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Service Devices At Health Centers.
        /// </summary>
        public static string CenterArchive {
            get {
                return ResourceManager.GetString("CenterArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Center Devices.
        /// </summary>
        public static string CenterDevices {
            get {
                return ResourceManager.GetString("CenterDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Center Device Schedule.
        /// </summary>
        public static string CenterDeviceSchedual {
            get {
                return ResourceManager.GetString("CenterDeviceSchedual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Center Device PPM Notification.
        /// </summary>
        public static string CenterDeviceScheduleNotification {
            get {
                return ResourceManager.GetString("CenterDeviceScheduleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Departments Of Health Centers.
        /// </summary>
        public static string CenterDeviceUnits {
            get {
                return ResourceManager.GetString("CenterDeviceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Center Name.
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Centers Settings Of Reports PPM.
        /// </summary>
        public static string CenterPPMReportSettings {
            get {
                return ResourceManager.GetString("CenterPPMReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Centers Report Settings.
        /// </summary>
        public static string CenterReportSettings {
            get {
                return ResourceManager.GetString("CenterReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Center Requests.
        /// </summary>
        public static string CenterRequests {
            get {
                return ResourceManager.GetString("CenterRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Centers.
        /// </summary>
        public static string Centers {
            get {
                return ResourceManager.GetString("Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Dates.
        /// </summary>
        public static string ChooseDates {
            get {
                return ResourceManager.GetString("ChooseDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Notification.
        /// </summary>
        public static string CloseNotification {
            get {
                return ResourceManager.GetString("CloseNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Of Warranty Company.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name Of Warranty Company.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number Of Warranty Company.
        /// </summary>
        public static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Number.
        /// </summary>
        public static string ComputerNumber {
            get {
                return ResourceManager.GetString("ComputerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Agent Will Be Called Up.
        /// </summary>
        public static string Confirm2 {
            get {
                return ResourceManager.GetString("Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Agent Was Called Up.
        /// </summary>
        public static string Confirm3 {
            get {
                return ResourceManager.GetString("Confirm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrator Will Be Have Called Up.
        /// </summary>
        public static string Confirm4 {
            get {
                return ResourceManager.GetString("Confirm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrator Have Been Called Up.
        /// </summary>
        public static string Confirm5 {
            get {
                return ResourceManager.GetString("Confirm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Order Executed.
        /// </summary>
        public static string Confirm8 {
            get {
                return ResourceManager.GetString("Confirm8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Repair.
        /// </summary>
        public static string Confirming {
            get {
                return ResourceManager.GetString("Confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Fixed.
        /// </summary>
        public static string Confrimed {
            get {
                return ResourceManager.GetString("Confrimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody Official.
        /// </summary>
        public static string CustodyOfficial {
            get {
                return ResourceManager.GetString("CustodyOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Of Custody Official.
        /// </summary>
        public static string CustodyOPhone {
            get {
                return ResourceManager.GetString("CustodyOPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الأجهزة بجميع المراكز الصحية.
        /// </summary>
        public static string d1 {
            get {
                return ResourceManager.GetString("d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح الغير منجزة بجميع المراكز الصحية خلال فترة.
        /// </summary>
        public static string d10 {
            get {
                return ResourceManager.GetString("d10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح المنجزة بجميع المراكز الصحية خلال فترة حسب تاريخ الأصلاح.
        /// </summary>
        public static string d11 {
            get {
                return ResourceManager.GetString("d11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح الغير منجزة لمركز صحي.
        /// </summary>
        public static string d12 {
            get {
                return ResourceManager.GetString("d12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلال فترة.
        /// </summary>
        public static string d13 {
            get {
                return ResourceManager.GetString("d13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح المنجزة لمركز صحي.
        /// </summary>
        public static string d14 {
            get {
                return ResourceManager.GetString("d14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلال فترة حسب تاريخ الأصلاح.
        /// </summary>
        public static string d15 {
            get {
                return ResourceManager.GetString("d15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعطل.
        /// </summary>
        public static string d16 {
            get {
                return ResourceManager.GetString("d16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت العطل.
        /// </summary>
        public static string d17 {
            get {
                return ResourceManager.GetString("d17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الأصلاح.
        /// </summary>
        public static string d18 {
            get {
                return ResourceManager.GetString("d18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فترة التعطل.
        /// </summary>
        public static string d19 {
            get {
                return ResourceManager.GetString("d19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الأجهزة لمركز صحي.
        /// </summary>
        public static string d2 {
            get {
                return ResourceManager.GetString("d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح الغير منجزة لمركز صحي.
        /// </summary>
        public static string d20 {
            get {
                return ResourceManager.GetString("d20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح المنجزة لمركز صحي.
        /// </summary>
        public static string d21 {
            get {
                return ResourceManager.GetString("d21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح الغير منجزة لمركز صحي.
        /// </summary>
        public static string d22 {
            get {
                return ResourceManager.GetString("d22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح المنجزة لمركز صحي.
        /// </summary>
        public static string d23 {
            get {
                return ResourceManager.GetString("d23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسم.
        /// </summary>
        public static string d24 {
            get {
                return ResourceManager.GetString("d24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الاجهزة لمركز صحي.
        /// </summary>
        public static string d25 {
            get {
                return ResourceManager.GetString("d25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الاجهزة لمركز صحي.
        /// </summary>
        public static string d26 {
            get {
                return ResourceManager.GetString("d26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح الغير منجزة خلال فترة.
        /// </summary>
        public static string d27 {
            get {
                return ResourceManager.GetString("d27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح المنجزة خلال الفترة حسب تاريخ الأصلاح.
        /// </summary>
        public static string d28 {
            get {
                return ResourceManager.GetString("d28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح الغير منجزة في.
        /// </summary>
        public static string d29 {
            get {
                return ResourceManager.GetString("d29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم المركز.
        /// </summary>
        public static string d3 {
            get {
                return ResourceManager.GetString("d3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات الأصلاح المنجزة في.
        /// </summary>
        public static string d30 {
            get {
                return ResourceManager.GetString("d30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة أجهزة.
        /// </summary>
        public static string d31 {
            get {
                return ResourceManager.GetString("d31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الاجهزة بالمستشفى.
        /// </summary>
        public static string d32 {
            get {
                return ResourceManager.GetString("d32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الجهاز.
        /// </summary>
        public static string d4 {
            get {
                return ResourceManager.GetString("d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة المصنعة.
        /// </summary>
        public static string d5 {
            get {
                return ResourceManager.GetString("d5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموديل.
        /// </summary>
        public static string d6 {
            get {
                return ResourceManager.GetString("d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي.
        /// </summary>
        public static string d7 {
            get {
                return ResourceManager.GetString("d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string d8 {
            get {
                return ResourceManager.GetString("d8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الكمبيوتر.
        /// </summary>
        public static string d9 {
            get {
                return ResourceManager.GetString("d9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requsts Of Device Malfunction.
        /// </summary>
        public static string DamageRequest {
            get {
                return ResourceManager.GetString("DamageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Data.
        /// </summary>
        public static string Daman {
            get {
                return ResourceManager.GetString("Daman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Expiry Date Of Warranty.
        /// </summary>
        public static string DamanExpireDate {
            get {
                return ResourceManager.GetString("DamanExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Warranty.
        /// </summary>
        public static string DamanOut {
            get {
                return ResourceManager.GetString("DamanOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Status.
        /// </summary>
        public static string DamanStatus {
            get {
                return ResourceManager.GetString("DamanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered With Warranty.
        /// </summary>
        public static string DamanUnder {
            get {
                return ResourceManager.GetString("DamanUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Index.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Date.
        /// </summary>
        public static string DeleteDate {
            get {
                return ResourceManager.GetString("DeleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Health Center Requests.
        /// </summary>
        public static string DeletedCenterRequests {
            get {
                return ResourceManager.GetString("DeletedCenterRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Requests.
        /// </summary>
        public static string DeletedRequests {
            get {
                return ResourceManager.GetString("DeletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted User.
        /// </summary>
        public static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reason.
        /// </summary>
        public static string DeleteReason {
            get {
                return ResourceManager.GetString("DeleteReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Class.
        /// </summary>
        public static string DeviceCategory {
            get {
                return ResourceManager.GetString("DeviceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Categories Chart.
        /// </summary>
        public static string DeviceCategoryChart {
            get {
                return ResourceManager.GetString("DeviceCategoryChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model.
        /// </summary>
        public static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Of PPM.
        /// </summary>
        public static string DevicePPM {
            get {
                return ResourceManager.GetString("DevicePPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Devices schedule.
        /// </summary>
        public static string DeviceSchedual {
            get {
                return ResourceManager.GetString("DeviceSchedual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Device PPM Notification.
        /// </summary>
        public static string DeviceScheduleNotification {
            get {
                return ResourceManager.GetString("DeviceScheduleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Of Devices.
        /// </summary>
        public static string DevicesReport {
            get {
                return ResourceManager.GetString("DevicesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Types Chart.
        /// </summary>
        public static string DeviceTypeChart {
            get {
                return ResourceManager.GetString("DeviceTypeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Types.
        /// </summary>
        public static string DeviceTypes {
            get {
                return ResourceManager.GetString("DeviceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Department Of Hospital.
        /// </summary>
        public static string DeviceUnit {
            get {
                return ResourceManager.GetString("DeviceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Departments Of Hospital.
        /// </summary>
        public static string DeviceUnits {
            get {
                return ResourceManager.GetString("DeviceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Department Chart.
        /// </summary>
        public static string DeviceUnitsChart {
            get {
                return ResourceManager.GetString("DeviceUnitsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Of Deparments’ Device.
        /// </summary>
        public static string DeviceUnitsReport {
            get {
                return ResourceManager.GetString("DeviceUnitsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Number Of Notices That Have Been Done.
        /// </summary>
        public static string DoneCount {
            get {
                return ResourceManager.GetString("DoneCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer Name.
        /// </summary>
        public static string EngineerName {
            get {
                return ResourceManager.GetString("EngineerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineers.
        /// </summary>
        public static string Engineers {
            get {
                return ResourceManager.GetString("Engineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No PPM Print.
        /// </summary>
        public static string f1 {
            get {
                return ResourceManager.GetString("f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Has Been Printed.
        /// </summary>
        public static string f2 {
            get {
                return ResourceManager.GetString("f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Not Printed.
        /// </summary>
        public static string f3 {
            get {
                return ResourceManager.GetString("f3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Validity.
        /// </summary>
        public static string FullPowers {
            get {
                return ResourceManager.GetString("FullPowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Validity (No  Delete).
        /// </summary>
        public static string FullPowersWithoutDelete {
            get {
                return ResourceManager.GetString("FullPowersWithoutDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Validity (No  Delete &amp; No Edit ).
        /// </summary>
        public static string FullPowersWithoutDeleteAndEdit {
            get {
                return ResourceManager.GetString("FullPowersWithoutDeleteAndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Validity (With No Editing On System Settings).
        /// </summary>
        public static string FullPowersWithoutSettings {
            get {
                return ResourceManager.GetString("FullPowersWithoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PPM.
        /// </summary>
        public static string GeneratePPM {
            get {
                return ResourceManager.GetString("GeneratePPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Report.
        /// </summary>
        public static string GetReport {
            get {
                return ResourceManager.GetString("GetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string HasNoPenddingRequests {
            get {
                return ResourceManager.GetString("HasNoPenddingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed.
        /// </summary>
        public static string HasPenddingRequests {
            get {
                return ResourceManager.GetString("HasPenddingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device PPM Schedule For Hospital.
        /// </summary>
        public static string HDeviceSchedual {
            get {
                return ResourceManager.GetString("HDeviceSchedual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Last PPM.
        /// </summary>
        public static string HideLastModification {
            get {
                return ResourceManager.GetString("HideLastModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Service Devices At Hospital.
        /// </summary>
        public static string HospitalArchive {
            get {
                return ResourceManager.GetString("HospitalArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string IdentifyUrSelf {
            get {
                return ResourceManager.GetString("IdentifyUrSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Request List.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة _A.
        /// </summary>
        public static string j1 {
            get {
                return ResourceManager.GetString("j1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة_B.
        /// </summary>
        public static string j2 {
            get {
                return ResourceManager.GetString("j2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة_C.
        /// </summary>
        public static string j3 {
            get {
                return ResourceManager.GetString("j3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Months.
        /// </summary>
        public static string Last3Months {
            get {
                return ResourceManager.GetString("Last3Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 Months.
        /// </summary>
        public static string Last6Months {
            get {
                return ResourceManager.GetString("Last6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last PPM.
        /// </summary>
        public static string LastModification {
            get {
                return ResourceManager.GetString("LastModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Validity(Edit System Settings).
        /// </summary>
        public static string LimitedPowerEditSystemSettingOnly {
            get {
                return ResourceManager.GetString("LimitedPowerEditSystemSettingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Of Devices Movement.
        /// </summary>
        public static string MovementRequest {
            get {
                return ResourceManager.GetString("MovementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name In Arabic.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name In English.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of The Applicant.
        /// </summary>
        public static string NameOfTheApplicant {
            get {
                return ResourceManager.GetString("NameOfTheApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Are No Health Centers.
        /// </summary>
        public static string NoCenters {
            get {
                return ResourceManager.GetString("NoCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Warranty.
        /// </summary>
        public static string NoDaman {
            get {
                return ResourceManager.GetString("NoDaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data To Be Shown.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confrimed.
        /// </summary>
        public static string NotConfrimed {
            get {
                return ResourceManager.GetString("NotConfrimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Number Of Notices That Have Not Been Done.
        /// </summary>
        public static string NotDoneCount {
            get {
                return ResourceManager.GetString("NotDoneCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Scheduled Devices.
        /// </summary>
        public static string NotScheduledDevices {
            get {
                return ResourceManager.GetString("NotScheduledDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Only For View.
        /// </summary>
        public static string PowersForViewOnly {
            get {
                return ResourceManager.GetString("PowersForViewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Sticker.
        /// </summary>
        public static string PPM {
            get {
                return ResourceManager.GetString("PPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print State PPM.
        /// </summary>
        public static string PPM45 {
            get {
                return ResourceManager.GetString("PPM45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Added.
        /// </summary>
        public static string PPMAdded {
            get {
                return ResourceManager.GetString("PPMAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Date.
        /// </summary>
        public static string PPMDate {
            get {
                return ResourceManager.GetString("PPMDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Report.
        /// </summary>
        public static string PPMReport {
            get {
                return ResourceManager.GetString("PPMReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Of Reports PPM.
        /// </summary>
        public static string PPMReportSettings {
            get {
                return ResourceManager.GetString("PPMReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Sticker Text.
        /// </summary>
        public static string PPMStickerText {
            get {
                return ResourceManager.GetString("PPMStickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Will be Added.
        /// </summary>
        public static string PPMWillbeAdded {
            get {
                return ResourceManager.GetString("PPMWillbeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Requests.
        /// </summary>
        public static string PreviousRequests {
            get {
                return ResourceManager.GetString("PreviousRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Barcode.
        /// </summary>
        public static string PrintBarCode {
            get {
                return ResourceManager.GetString("PrintBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Health Center Report Template.
        /// </summary>
        public static string PrintHealthCenterReportTemplate {
            get {
                return ResourceManager.GetString("PrintHealthCenterReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Hospital Report Template.
        /// </summary>
        public static string PrintHospitalReportTemplate {
            get {
                return ResourceManager.GetString("PrintHospitalReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print PPM Frist.
        /// </summary>
        public static string PrintPPMFrist {
            get {
                return ResourceManager.GetString("PrintPPMFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string ReportDate {
            get {
                return ResourceManager.GetString("ReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Of Reports.
        /// </summary>
        public static string ReportSettings {
            get {
                return ResourceManager.GetString("ReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Of Requests.
        /// </summary>
        public static string RequestChart {
            get {
                return ResourceManager.GetString("RequestChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Stage.
        /// </summary>
        public static string RequestProcess {
            get {
                return ResourceManager.GetString("RequestProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Of Departments.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Of Request With No Bar Code.
        /// </summary>
        public static string RequestWithNoBarCode {
            get {
                return ResourceManager.GetString("RequestWithNoBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibilities.
        /// </summary>
        public static string Responsibility {
            get {
                return ResourceManager.GetString("Responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Continue.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM Count.
        /// </summary>
        public static string ScheduleCount {
            get {
                return ResourceManager.GetString("ScheduleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than One Number Is Not Allowed.
        /// </summary>
        public static string ScheduleCountError {
            get {
                return ResourceManager.GetString("ScheduleCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Devices.
        /// </summary>
        public static string ScheduledDevices {
            get {
                return ResourceManager.GetString("ScheduledDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device Under Warranty.
        /// </summary>
        public static string ShowDaman {
            get {
                return ResourceManager.GetString("ShowDaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Last PPM.
        /// </summary>
        public static string ShowLastModification {
            get {
                return ResourceManager.GetString("ShowLastModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last PPM.
        /// </summary>
        public static string ShowLastPPM {
            get {
                return ResourceManager.GetString("ShowLastPPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Request With No Bar Code.
        /// </summary>
        public static string ShowRequestWithNoBarCode {
            get {
                return ResourceManager.GetString("ShowRequestWithNoBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Photo.
        /// </summary>
        public static string SignImg {
            get {
                return ResourceManager.GetString("SignImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Number Of Notices.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Preview.
        /// </summary>
        public static string TotalPreview {
            get {
                return ResourceManager.GetString("TotalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Department.
        /// </summary>
        public static string ToUnit {
            get {
                return ResourceManager.GetString("ToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfar To Unit.
        /// </summary>
        public static string TransfarToUnit {
            get {
                return ResourceManager.GetString("TransfarToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Of Stickers &amp; Logo.
        /// </summary>
        public static string WebsiteData {
            get {
                return ResourceManager.GetString("WebsiteData", resourceCulture);
            }
        }
    }
}
